name: Live world cup 2026 pipeline supabase

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install pandas numpy requests python-dotenv joblib supabase scikit-learn sqlalchemy

    # Run scripts using Supabase Secrets
    - name: Run Loader & Cleaner
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python scrape/loader.py

    #- name: Fetch Live 2026 Fixtures
    #  env:
    #    FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
    #    SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    #    SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    #  run: python scrape/live_scrape.py
    #  continue-on-error: true

    - name: Download Trained Model Asset
      run: |
        mkdir -p model
        curl -L -o model/model.pkl https://github.com/ch-sophie/worldcup-predictions/releases/download/v1.0.0/model.pkl

    - name: Run Predictions
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python model/predict_supabase.py

    - name: Run Tournament Simulation
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python model/simulate_supabase.py