name: Live world cup 2026 pipeline

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        #cache: 'pip' # Speeds up subsequent runs

    - name: Install Dependencies
      run: |
        pip install pandas sqlalchemy sqlite3 numpy

    # 1. Load the raw data/scraped CSVs into the SQLite DB
    - name: Load Data into DB
      run: python loader.py

    # 2. Process, clean, and generate features
    - name: Run Data Cleaner and Feature Engineering
      run: python cleaner.py

    # 3. Saves the SQLite file backup right back into repository
    - name: Commit and Push SQLite Changes
      run: |
        git config --global user.name "GitHub Action Automation"
        git config --global user.email "actions@github.com"
        git add world_cup_2026.db
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Sync local SQLite backup" && git push)