name: Live world cup 2026 pipeline

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install pandas sqlalchemy numpy psycopg2-binary python-dotenv requests

    # 1. Load the raw Kaggle CSVs and clean them
    - name: Load Data into DB
      run: python scrape/loader.py #with cleaner.py

    # 2. Fetch live 2026 match results from football-data.org
    - name: Fetch Live 2026 Fixtures
      run: python scrape/live_scraping.py

    # 3. Commit SQLite and any data changes back to repo
    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action Automation"
        git config --global user.email "actions@github.com"
        git add data/
        git add -f worldcup_2026.db
        git diff-index --quiet HEAD || git commit -m "Automated data sync"
        git push